import { NextResponse } from "next/server";
import { proxyDownload } from "@/lib/bff";

// BFF for the "Κατεβάστε το πρότυπο αρχείο CSV" link. The browser hits this
// same-origin URL directly from an <a download>, so the file has to arrive as
// bytes with its Content-Disposition intact — see proxyDownload. The template
// carries a UTF-8 BOM that Excel needs, which is precisely what would be lost
// by round-tripping it through NextResponse.json().
//
// The template is generated by server/imports.py rather than written into this
// bundle, so the columns a user is shown and the columns the parser matches on
// cannot drift apart.
const KINDS: Record<string, string> = {
  clients: "protypo-pelaton.csv",
  transactions: "protypo-kiniseon.csv",
};

export async function GET(
  _req: Request,
  { params }: { params: Promise<{ kind: string }> },
) {
  const { kind } = await params;
  const filename = KINDS[kind];
  // Whitelisted rather than interpolated: `kind` comes from the URL, and
  // forwarding it unchecked would aim this proxy at an arbitrary backend path.
  if (!filename) {
    return NextResponse.json(
      { error: "Άγνωστο πρότυπο αρχείο." },
      { status: 404 },
    );
  }
  return proxyDownload(`/api/import/templates/${kind}`, {
    fallback: "Αποτυχία λήψης προτύπου.",
    filename,
  });
}
